# Generated by Django 2.2.5 on 2020-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='mac',
            field=models.CharField(max_length=18),
        ),
    ]
