# Generated by Django 2.2.5 on 2020-02-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=1000)),
                ('sn', models.CharField(max_length=16)),
            ],
        ),
    ]
